services:
  auth-service-db:
    image: postgres:16.4
    container_name: auth-service-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    volumes:
      - auth-service-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin_user -d db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./auth-service
    container_name: auth-service
    depends_on:
      auth-service-db:
        condition: service_healthy
#    ports:
#      - "8080:8080"
    env_file: 
      - ./secrets/auth.env

  webbot-service:
    build: ./webbot-service
    container_name: webbot-service
#    ports:
#      - "8081:8081"
    env_file:
      - ./secrets/webbot.env

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - auth-service
      - webbot-service
    ports:
      - "8082:8082"
    env_file:
      - ./secrets/auth.env
    restart: unless-stopped

volumes:
  auth-service-db-data: